Ckleanup language and update URLs
apache/maven-javadoc-plugin pull request #172
Opened 2022-10-30 18:51 UTC by elharo

@michael-o

2022-10-30 19:05 UTC, michael-o requested changes

2022-10-30 19:05 UTC, michael-o commented on src/site/apt/examples/fix-javadocs.apt.vm
> + a SCM, so you cab revert if a problem occurs. You can also add <<<-DoutputDirectory=/path/to/dir>>>
cab or can?

2022-11-05 20:32 UTC, elharo commented on src/site/apt/examples/fix-javadocs.apt.vm
> + a SCM, so you cab revert if a problem occurs. You can also add <<<-DoutputDirectory=/path/to/dir>>>
can. Thanks for the catch. Fixed.

2022-11-13 15:13 UTC, michael-o approved these changes

2022-12-22 18:56 UTC, merged