Refactoring done in various parts of code.
apache/maven-javadoc-plugin pull request #203
Opened 2023-04-05 16:45 UTC by jaymulani

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MJAVADOC) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MJAVADOC-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MJAVADOC-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify -Prun-its` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

2023-05-20 15:33 UTC, jaymulani commented
.

2023-07-01 10:44 UTC, elharo requested changes
There are a lot of small issues here, but overall I don't see the reason for any of this.

2023-07-01 10:44 UTC, elharo commented on pom.xml
> +          <groupId>org.apache.maven.plugins</groupId>
indentation is off

2023-07-01 10:44 UTC, elharo commented on src/main/java/org/apache/maven/plugins/javadoc/AbstractFixJavadocMojo.java
> +    // Refactoring : Extract Method
needless comment

2023-07-01 10:44 UTC, elharo commented on src/main/java/org/apache/maven/plugins/javadoc/AbstractFixJavadocMojo.java
> +//     * @param stringWriter not null
why?

2023-07-02 12:17 UTC, closed without merging