[MJAVADOC-762] don't share state between tests
apache/maven-javadoc-plugin pull request #218
Opened 2023-07-10 10:54 UTC by elharo

2023-09-25 11:20 UTC, michael-o requested changes

2023-09-25 11:20 UTC, michael-o commented on src/test/java/org/apache/maven/plugins/javadoc/JavadocReportTest.java
> +        Path folder = Files.createTempDirectory("JavadocReportTest");
directory, not folder

2023-09-25 11:32 UTC, elharo commented on src/test/java/org/apache/maven/plugins/javadoc/JavadocReportTest.java
> +        Path folder = Files.createTempDirectory("JavadocReportTest");
done

2023-09-25 11:43 UTC, michael-o approved these changes
Good to merge after CI completion.

2023-09-25 13:32 UTC, merged

2025-06-10 00:58 UTC, jira-importer commented
Resolve #1140